// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://scnaqjixwuqakppnahfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjbmFxaml4d3VxYWtwcG5haGZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5NTUyOTQsImV4cCI6MjA3NzUzMTI5NH0.zFvMWB-mSb2bjmnKJAUOZUQdjCAfz9l9xFc3ihhejKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);